[project]
name = "deribit-tracker"
version = "0.1.0"
description = "Deribit Price Tracker API"
authors = [
    {name = "script-logic",email = "dev.scriptlogic@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "app"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
