"""create_price_ticks_table

Revision ID: 19cfef6b2cba
Revises:
Create Date: 2026-01-25 21:49:52.138420

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "19cfef6b2cba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_ticks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_ticks_ticker"), "price_ticks", ["ticker"], unique=False
    )
    op.create_index(
        op.f("ix_price_ticks_timestamp"),
        "price_ticks",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_ticks_timestamp"), table_name="price_ticks")
    op.drop_index(op.f("ix_price_ticks_ticker"), table_name="price_ticks")
    op.drop_table("price_ticks")
    # ### end Alembic commands ###
